//https://exercisedb.p.rapidapi.com/exercises/name/all%20fours%20squad%20stretch
/*
const axios = require('axios');

const options = {
  method: 'GET',
  url: 'https://exercisedb.p.rapidapi.com/exercises/name/all%20fours%20squad%20stretch',
  params: {limit: '10'},
  headers: {
    'X-RapidAPI-Key': 'eca292af59msh8ffdd873adb52a1p1f8550jsndcef5c0e0471',
    'X-RapidAPI-Host': 'exercisedb.p.rapidapi.com'
  }
};

try {
	const response = await axios.request(options);
	console.log(response.data);
} catch (error) {
	console.error(error);
}
*/

// const fs = require('fs');

// const allTitles = [
//   '3/4 sit-up',
//   '45° side bend',
//   'air bike',
//   'all fours squad stretch',
//   'alternate heel touchers',
//   'alternate lateral pulldown',
//   'ankle circles',
//   'archer pull up',
//   'archer push up',
//   'arm slingers hanging bent knee legs',
//   'arm slingers hanging straight legs',
//   'arms apart circular toe touch (male)',
//   'arms overhead full sit-up (male)',
//   'assisted chest dip (kneeling)',
//   'assisted hanging knee raise',
//   'assisted hanging knee raise with throw down',
//   'assisted lying calves stretch',
//   'assisted lying glutes stretch',
//   'assisted lying gluteus and piriformis stretch',
//   'assisted lying leg raise with lateral throw down',
//   'assisted lying leg raise with throw down',
//   'assisted motion russian twist',
//   'assisted parallel close grip pull-up',
//   'assisted prone hamstring',
//   'assisted prone lying quads stretch',
//   'assisted prone rectus femoris stretch',
//   'assisted pull-up',
//   'assisted seated pectoralis major stretch with stability ball',
//   'assisted side lying adductor stretch',
//   'assisted sit-up',
//   'assisted standing chin-up',
//   'assisted standing pull-up',
//   'assisted standing triceps extension (with towel)',
//   'assisted triceps dip (kneeling)',
//   'assisted wide-grip chest dip (kneeling)',
//   'astride jumps (male)',
//   'back and forth step',
//   'back extension on exercise ball',
//   'back lever',
//   'back pec stretch',
//   'backward jump',
//   'balance board',
//   'band alternating biceps curl',
//   'band alternating v-up',
//   'band assisted pull-up',
//   'band assisted wheel rollerout',
//   'band bench press',
//   'band bent-over hip extension',
//   'band bicycle crunch',
//   'band close-grip pulldown',
//   'band close-grip push-up',
//   'band concentration curl',
//   'band fixed back close grip pulldown',
//   'band fixed back underhand pulldown',
//   'band front lateral raise',
//   'band front raise',
//   'band hip lift',
//   'band horizontal pallof press',
//   'band jack knife sit-up',
//   'band kneeling one arm pulldown',
//   'band kneeling twisting crunch',
//   'band lying hip internal rotation',
//   'band lying straight leg raise',
//   'band one arm overhead biceps curl',
//   'band one arm single leg split squat',
//   'band one arm standing low row',
//   'band one arm twisting chest press',
//   'band one arm twisting seated row',
//   'band pull through',
//   'band push sit-up',
//   'band reverse fly',
//   'band reverse wrist curl',
//   'band seated hip internal rotation',
//   'band seated twist',
//   'band shoulder press',
//   'band shrug',
//   'band side triceps extension',
//   'band single leg calf raise',
//   'band single leg reverse calf raise',
//   'band single leg split squat',
//   'band squat',
//   'band squat row',
//   'band standing crunch',
//   'band standing rear delt row',
//   'band standing twisting crunch',
//   'band step-up',
//   'band stiff leg deadlift',
//   'band straight back stiff leg deadlift',
//   'band straight leg deadlift',
//   'band twisting overhead press',
//   'band two legs calf raise - (band under both legs) v. 2',
//   'band underhand pulldown',
//   'band v-up',
//   'band vertical pallof press',
//   'band wrist curl',
//   'band y-raise',
//   'barbell alternate biceps curl',
//   'barbell bench front squat',
//   'barbell bench press',
//   'barbell bench squat',
//   'cable cross-over lateral pulldown',
//   'cable cross-over revers fly',
//   'cable cross-over variation',
//   'cable curl',
//   'cable deadlift',
//   'cable decline fly',
//   'cable decline one arm press',
//   'cable decline press',
//   'cable decline seated wide-grip row',
//   'cable drag curl',
//   'cable floor seated wide-grip row',
//   'cable forward raise',
//   'cable front raise',
//   'cable front shoulder raise',
//   'cable hammer curl (with rope)',
//   'cable high pulley overhead tricep extension',
//   'cable high row (kneeling)',
//   'cable hip adduction',
//   'cable incline bench press',
//   'crab twist toe touch',
//   'cross body crunch',
//   'crunch (hands overhead)',
//   'crunch (on stability ball)',
//   'crunch (on stability ball, arms straight)',
//   'crunch floor',
//   'curl-up',
//   'curtsey squat',
//   'cycle cross trainer',
//   'dead bug',
//   'decline crunch',
//   'decline push-up',
//   'decline sit-up',
//   'deep push up',
//   'diamond push-up',
//   'donkey calf raise',
//   'drop push up',
//   'dumbbell alternate biceps curl',
//   'dumbbell alternate biceps curl (with arm blaster)',
//   'dumbbell alternate hammer preacher curl',
//   'dumbbell alternate preacher curl',
//   'dumbbell alternate seated hammer curl',
//   'dumbbell alternate side press',
//   'dumbbell alternating bicep curl with leg raised on exercise ball',
//   'dumbbell alternating seated bicep curl on exercise ball',
//   'dumbbell arnold press',
//   'dumbbell arnold press v. 2',
//   'dumbbell around pullover',
//   'dumbbell bench press',
//   'dumbbell bench seated press',
//   'dumbbell bench squat',
//   'dumbbell bent over row',
//   'dumbbell bicep curl lunge with bowling motion',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'dumbbell bicep curl with stork stance',
//   'dumbbell biceps curl',
//   'dumbbell biceps curl (with arm blaster)',
//   'dumbbell biceps curl reverse',
//   'dumbbell biceps curl squat',
//   'dumbbell biceps curl v sit on bosu ball',
//   'dumbbell burpee',
//   'dumbbell clean',
//   'dumbbell close grip press',
//   'dumbbell close-grip press',
//   'dumbbell concentration curl',
//   'dumbbell contralateral forward lunge',
//   'dumbbell cross body hammer curl',
//   'dumbbell cross body hammer curl v. 2',
//   'dumbbell cuban press',
//   'dumbbell cuban press v. 2',
//   'dumbbell deadlift',
//   'dumbbell decline bench press',
//   'dumbbell decline fly',
//   'dumbbell decline hammer press',
//   'dumbbell decline one arm fly',
//   'dumbbell decline one arm hammer press',
//   'dumbbell decline shrug',
//   'dumbbell decline shrug v. 2',
//   'dumbbell decline triceps extension',
//   'dumbbell decline twist fly',
//   'dumbbell finger curls',
//   'dumbbell fly',
//   'dumbbell fly on exercise ball',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell front raise',
//   'dumbbell front raise v. 2',
//   'dumbbell full can lateral raise',
//   'dumbbell goblet squat',
//   'dumbbell hammer curl',
//   'dumbbell hammer curl on exercise ball',
//   'dumbbell hammer curl v. 2',
//   'dumbbell hammer curls (with arm blaster)',
//   'dumbbell high curl',
//   'dumbbell incline alternate press',
//   'dumbbell incline bench press',
//   'dumbbell incline biceps curl',
//   'dumbbell incline breeding',
//   'dumbbell incline curl',
//   'dumbbell incline curl v. 2',
//   'dumbbell incline fly',
//   'dumbbell incline fly on exercise ball',
//   'dumbbell incline hammer curl',
//   'dumbbell incline hammer press',
//   'dumbbell incline hammer press on exercise ball',
//   'dumbbell incline inner biceps curl',
//   'dumbbell incline one arm fly',
//   'dumbbell incline one arm fly on exercise ball',
//   'dumbbell incline one arm hammer press',
//   'dumbbell incline one arm hammer press on exercise ball',
//   'dumbbell incline one arm lateral raise',
//   'dumbbell incline one arm press',
//   'dumbbell incline one arm press on exercise ball',
//   'dumbbell incline palm-in press',
//   'dumbbell incline press on exercise ball',
//   'dumbbell incline raise',
//   'dumbbell incline rear lateral raise',
//   'dumbbell incline row',
//   'dumbbell incline shoulder raise',
//   'dumbbell incline shrug',
//   'dumbbell incline t-raise',
//   'ez bar seated close grip concentration curl',
//   'ez bar standing french press',
//   'ez barbell anti gravity press',
//   'ez barbell close grip preacher curl',
//   'ez barbell close-grip curl',
//   'ez barbell curl',
//   'ez barbell decline close grip face press',
//   'ez barbell decline triceps extension',
//   'ez barbell incline triceps extension',
//   'ez barbell jm bench press',
//   'ez barbell reverse grip curl',
//   'ez barbell reverse grip preacher curl',
//   'ez barbell seated curls',
//   'ez barbell seated triceps extension',
//   'ez barbell spider curl',
//   'ez barbell spider curl',
//   'ez-bar biceps curl (with arm blaster)',
//   'ez-bar close-grip bench press',
//   'ez-barbell standing wide grip biceps curl',
//   'farmers walk',
//   'finger curls',
//   'flag',
//   'flexion leg sit up (bent knee)',
//   'flexion leg sit up (straight arm)',
//   'floor fly (with barbell)',
//   'flutter kicks',
//   'forward jump',
//   'forward lunge (male)',
//   'frankenstein squat',
//   'frog crunch',
//   'frog planche',
//   'front lever',
//   'front lever reps',
//   'front plank with twist',
//   'full maltese',
//   'full planche',
//   'full planche push-up',
//   'gironda sternum chin',
//   'glute bridge march',
//   'glute bridge two legs on bench (male)',
//   'glute-ham raise',
//   'gorilla chin',
//   'groin crunch',
//   'hack calf raise',
//   'hack one leg calf raise',
//   'half knee bends (male)',
//   'half sit-up (male)',
//   'hamstring stretch',
//   'hands bike',
//   'hands clasped circular toe touch (male)',
//   'hands reversed clasped circular toe touch (male)',
//   'handstand',
//   'handstand push-up',
//   'hanging leg hip raise',
//   'hanging leg raise',
//   'hanging oblique knee raise',
//   'hanging pike',
//   'hanging straight leg hip raise',
//   'hanging straight leg raise',
//   'hanging straight twisting leg hip raise',
//   'high knee against wall',
//   'hip raise (bent knee)',
//   'hug keens to chest',
//   'hyght dumbbell fly',
//   'hyperextension',
//   'hyperextension (on bench)',
//   'impossible dips',
//   'inchworm',
//   'inchworm v. 2',
//   'incline close-grip push-up',
//   'incline leg hip raise (leg straight)',
//   'incline push up depth jump',
//   'incline push-up',
//   'incline push-up (on box)',
//   'incline reverse grip push-up',
//   'incline scapula push up',
//   'incline twisting sit-up',
//   'intermediate hip flexor and quad stretch',
//   'inverse leg curl (bench support)',
//   'inverse leg curl (on pull-up cable machine)',
//   'inverted row',
//   'inverted row bent knees',
//   'inverted row on bench',
//   'inverted row v. 2',
//   'inverted row with straps',
//   'iron cross stretch',
//   'isometric chest squeeze',
//   'isometric wipers',
//   'jack burpee',
//   'jack jump (male)',
//   'jackknife sit-up',
//   'janda sit-up',
//   'jump rope',
//   'jump squat',
//   'jump squat v. 2',
//   'kettlebell advanced windmill',
//   'kettlebell alternating hang clean',
//   'kettlebell alternating press',
//   'kettlebell alternating press on floor',
//   'kettlebell alternating renegade row',
// ];

// const randomTitlePick = [
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'front plank with twist',
//   'band concentration curl',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'front plank with twist',
//   'band concentration curl',
//   'inverted row on bench',
//   'dumbbell close-grip press',

//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'front plank with twist',
//   'band concentration curl',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'inverted row on bench',
//   'dumbbell close-grip press',
//   'hug keens to chest',
//   'band front lateral raise',
//   'band single leg reverse calf raise',
//   'band squat',
//   'crunch (hands overhead)',
//   'dumbbell goblet squat',
//   'barbell bench squat',
//   'band push sit-up',
//   'cable decline seated wide-grip row',
//   'assisted sit-up',
//   'dumbbell high curl',
//   'air bike',
//   'dumbbell incline curl',
//   'cable floor seated wide-grip row',
//   'dumbbell incline hammer press',
//   'dumbbell high curl',
//   'hands clasped circular toe touch (male)',
//   'intermediate hip flexor and quad stretch',
//   'band twisting overhead press',
//   'groin crunch',
//   'band squat',
//   'barbell bench press',
//   'full planche push-up',
//   'dumbbell alternate preacher curl',
//   'band one arm single leg split squat',
//   'hyperextension (on bench)',
//   'dumbbell hammer curl',
//   'half sit-up (male)',
//   'band push sit-up',
//   'jump squat v. 2',
//   'dumbbell forward lunge triceps extension',
//   'dumbbell bicep curl lunge with bowling motion',
//   'isometric wipers',
//   'cable front raise',
//   'jack burpee',
//   'ez barbell anti gravity press',
//   'ez bar seated close grip concentration curl',
//   'glute-ham raise',
//   'hanging straight twisting leg hip raise',
//   'dumbbell biceps curl',
//   'barbell alternate biceps curl',
//   'jump rope',
//   'band y-raise',
//   'assisted pull-up',
//   'all fours squad stretch',
//   'jump squat v. 2',
//   'assisted prone hamstring',
//   'dumbbell cuban press',
//   '3/4 sit-up',
//   'dumbbell bench seated press',
//   'dumbbell incline row',
//   'band kneeling one arm pulldown',
//   'ez-bar biceps curl (with arm blaster)',
//   'assisted standing triceps extension (with towel)',
//   'dumbbell burpee',
//   'cable drag curl',
//   'hanging pike',
//   'band hip lift',
//   'cable decline seated wide-grip row',
//   'dumbbell incline raise',
//   'dumbbell decline one arm fly',
//   'frog crunch',
//   'dumbbell incline row',
//   'front plank with twist',
//   'band concentration curl',
//   'band standing crunch',
//   'jump rope',
//   'dumbbell decline twist fly',
//   'band side triceps extension',
//   'high knee against wall',
//   'assisted triceps dip (kneeling)',
//   'dumbbell incline fly on exercise ball',
//   'band standing rear delt row',
//   'isometric wipers',
//   'dumbbell concentration curl',
//   'farmers walk',
//   'balance board',
//   'dumbbell bench press',
//   'intermediate hip flexor and quad stretch',
//   'band squat',
//   'band bent-over hip extension',
//   'deep push up',
//   'isometric wipers',
//   'dumbbell decline bench press',
//   'incline push-up',
//   'band underhand pulldown',
//   'dumbbell front raise v. 2',
//   'incline reverse grip push-up',
//   'ez barbell spider curl',
//   'band assisted pull-up',
//   'dumbbell bicep curl on exercise ball with leg raised',
//   'ez-barbell standing wide grip biceps curl',
//   'dumbbell finger curls',
//   'front plank with twist',
//   'band concentration curl',
//   'inverted row on bench',
//   'dumbbell close-grip press',
// ];

// const arrOfProgId = [1, 2, 3, 4, 5, 6];

// const arrObjExercises = [];

// for (let i = 0; i < 864; i++) {

//   const progId = arrOfProgId[i % arrOfProgId.length]; // Get program id cyclically

//   const obj = {
//     program_id: progId,
//     exercise_title: randomTitlePick[i],
//     duration: 30,
//     rest_time: 20,
//     exercise_type: i % 2 == 0 ? 'morning' : 'evening',
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   };

//   arrObjExercises.push(obj);
// }
// const fsWritein = fs.writeFileSync(
//   'C:\\Users\\skhva\\OneDrive\\Desktop\\Elbrus\\Phase-3\\FINAL_PROJECT_ONLYFITS\\onlyfits\\server\\exercise_data\\exercise_data.json',
//   JSON.stringify(arrObjExercises)
// );
